apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: example-app-gwc
  annotations:
    konghq.com/gatewayclass-unmanaged: "true"
spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-app-gw
spec:
  gatewayClassName: example-app-gwc
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-testing
  annotations:
    konghq.com/strip-path: "true"
spec:
  parentRefs:
  - name: example-app-gw
  hostnames:
    - foo.tld # need to -H "Host: foo.tld" or it won't match
  rules:
  - matches:
    backendRefs:
    - name: my-example-service
      port: 80
